### ISSUE TITLE
synchronize copies man pages from local host

### ISSUE THREAD

**Issue by rubdos** [naftulikay/ansible-role-rust-dev#11]
Consider

```ansible
- name: sync man pages
  synchronize:
    src: "{{ rust_user_home }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/man/man1/"
    dest: "/usr/local/share/man/man1/"
  become: true
```
`synchronize` will rsync from the local computer (not from where Rust was just installed) to `dest` on the remote. I think this is a mistake; shouldn't this copy from the *new*/remote Rust install?

**Comment by naftulikay** [comment]
According [to the Ansible documentation](https://docs.ansible.com/ansible/latest/modules/synchronize_module.html), if both paths are absolute, files will be copied locally on the remote host. If you'd like to use a separate module to make this more explicit, PRs are welcome.

[Here is the line referred to above.](https://github.com/naftulikay/ansible-role-rust-dev/blob/master/tasks/main.yml#L64)

**Comment by rubdos** [comment]
### Examples:

```yaml
- name: Synchronize two directories on one remote host.
  synchronize:
    src: /first/absolute/path
    dest: /second/absolute/path
  delegate_to: "{{ inventory_hostname }}"
```

Mind the `delegate_to`. I don't see where in the Ansible documentation this is mentioned; they always seem to use `delegate_to` when copying locally on the remote.

I was trying your module yesterday, with as target user `builder`, which is different from my local user `rsmet`, and I had a file-not-found. It dumped the path that was not found, and `ls` of that path clearly existed on the remote machine.
